---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-executables-have-shebangs
- repo: https://github.com/pecigonzalo/pre-commit-terraform-vars.git
  rev: v1.0.0
  hooks:
  - id: terraform-vars
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt.git
  rev: 0.1.1
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --width, '150', --preserve-quotes]
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.80.0
  hooks:
  - id: terraform_fmt
  - id: terraform_validate
  - id: terraform_docs
    args:
    - '--args=--lockfile=false'
  - id: terraform_tflint
    args:
    - '--args=--only=terraform_deprecated_interpolation'
    - '--args=--only=terraform_deprecated_index'
    - '--args=--only=terraform_unused_declarations'
    - '--args=--only=terraform_comment_syntax'
    - '--args=--only=terraform_documented_outputs'
    - '--args=--only=terraform_documented_variables'
    - '--args=--only=terraform_typed_variables'
    - '--args=--only=terraform_module_pinned_source'
    - '--args=--only=terraform_naming_convention'
    - '--args=--only=terraform_required_version'
    - '--args=--only=terraform_required_providers'
    - '--args=--only=terraform_standard_module_structure'
    - '--args=--only=terraform_workspace_remote'
- repo: https://github.com/terraform-docs/terraform-docs.git
  rev: "v0.12.0"
  hooks:
  - id: terraform-docs-go
    args: ["markdown", "table", "--output-file", "README.md", "."]
